### ISSUE TITLE
Not returning seed/peer data in torrent client

### ISSUE THREAD

**Issue by AzukaChan** [petcap/bitstorm-sql#1]
Tried to get this working on my Windows webspace but ran into a small issue; When making a torrent and adding the tracker to the list of available trackers, torrent clients will show the tracker to be "working" however they are unable to successfully return any seed/peer data even though an entry has been made in the database.

**Comment by petcap** [comment]
Hi! As your original title mentioned, the client attempts to scrape the tracker. The way scraping works is that it replaces the string "announce" with "scrape" in the URL. If your tracker URL is https://server/announce.php, torrent clients may attempt scraping the URL https://server/scrape.php, which will result in an error 404.

The easiest quick fix is to rename announce.php to something else. Bitstorm does not implement scraping, although adding support should be fairly easy as scraping basically just tells the client the number of seeders and leechers.
